name: mi_clean_architecture
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.4
  flutter_bloc: 8.0.0
  kiwi: 4.0.1
  sprintf: 6.0.0
  intl: 0.17.0
  flutter_svg: 0.23.0+1
  cached_network_image: 3.1.0+1
  built_value: 8.1.3
  built_collection: 5.1.1
  google_fonts: ^2.1.0
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 1.0.4
  build_runner: 2.1.5
  kiwi_generator: 4.0.1
  built_value_generator: 8.1.3
  bloc_test: 9.0.1
  mockito: 5.0.16
  fake_async: 1.2.0

dependency_overrides:
  analyzer: 2.7.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
