import '../../api/entities/kids_model.dart';
import 'strings.dart';
import 'utils_import.dart';
 
    List<KidsModel> list = [
    KidsModel(
      id: '0',
      color: AppColors.primary,
      imagePath: Images.lion,
      title: Strings.lion,
      shortDescription: Strings.lionShortDesc,
      description: Strings.lionDesc,
      lifespan: Strings.lionLifeSpan,
      speed: Strings.lionSpeed,
    ),
    KidsModel(
      id: '1',
      color: AppColors.hippoColor,
      imagePath: Images.hippo,
      title: Strings.hippo,
      shortDescription: Strings.hippoShortDesc,
      description: Strings.hippoDesc,
      lifespan: Strings.hippoLifeSpan,
      speed: Strings.hippoSpeed,
    ),
    KidsModel(
      id: '2',
      color: AppColors.rabbitColor,
      imagePath: Images.rabbit,
      title: Strings.rabbit,
      shortDescription: Strings.rabbitShortDesc,
      description: Strings.rabbitDesc,
      lifespan: Strings.rabbitLifeSpan,
      speed: Strings.rabbitSpeed,
    ),
    KidsModel(
      id: '3',
      color: AppColors.giraffeColor,
      imagePath: Images.giraffe,
      title: Strings.giraffe,
      shortDescription: Strings.giraffeShortDesc,
      description: Strings.giraffeDesc,
      lifespan: Strings.giraffeLifeSpan,
      speed: Strings.giraffeSpeed,
    ),
    KidsModel(
      id: '4',
      color: AppColors.tigerColor,
      imagePath: Images.tiger,
      title: Strings.tiger,
      shortDescription: Strings.tigerShortDesc,
      description: Strings.tigerDesc,
      lifespan: Strings.tigerLifeSpan,
      speed: Strings.tigerSpeed,
    ),
    KidsModel(
      id: '5',
      color: AppColors.bearColor,
      imagePath: Images.bear,
      title: Strings.bear,
      shortDescription: Strings.bearShortDesc,
      description: Strings.bearDesc,
      lifespan: Strings.bearLifeSpan,
      speed: Strings.bearSpeed,
    ),
    KidsModel(
      id: '6',
      color: AppColors.primary,
      imagePath: Images.lion,
      title: Strings.lion,
      shortDescription: Strings.lionShortDesc,
      description: Strings.lionDesc,
      lifespan: Strings.lionLifeSpan,
      speed: Strings.lionSpeed,
    ),
    KidsModel(
      id: '7',
      color: AppColors.hippoColor,
      imagePath: Images.hippo,
      title: Strings.hippo,
      shortDescription: Strings.hippoShortDesc,
      description: Strings.hippoDesc,
      lifespan: Strings.hippoLifeSpan,
      speed: Strings.hippoSpeed,
    ),
    KidsModel(
      id: '8',
      color: AppColors.rabbitColor,
      imagePath: Images.rabbit,
      title: Strings.rabbit,
      shortDescription: Strings.rabbitShortDesc,
      description: Strings.rabbitDesc,
      lifespan: Strings.rabbitLifeSpan,
      speed: Strings.rabbitSpeed,
    ),
    KidsModel(
      id: '9',
      color: AppColors.giraffeColor,
      imagePath: Images.giraffe,
      title: Strings.giraffe,
      shortDescription: Strings.giraffeShortDesc,
      description: Strings.giraffeDesc,
      lifespan: Strings.giraffeLifeSpan,
      speed: Strings.giraffeSpeed,
    ),
    KidsModel(
      id: '10',
      color: AppColors.tigerColor,
      imagePath: Images.tiger,
      title: Strings.tiger,
      shortDescription: Strings.tigerShortDesc,
      description: Strings.tigerDesc,
      lifespan: Strings.tigerLifeSpan,
      speed: Strings.tigerSpeed,
    ),
    KidsModel(
      id: '11',
      color: AppColors.bearColor,
      imagePath: Images.bear,
      title: Strings.bear,
      shortDescription: Strings.bearShortDesc,
      description: Strings.bearDesc,
      lifespan: Strings.bearLifeSpan,
      speed: Strings.bearSpeed,
    ),
  ];